# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: User engagement

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: testdb

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - .db/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "^3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest poetry
        poetry install
    - name: Lint and format with ruff
      run: |
        ruff check
        ruff format
    - name: set environment variables
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: testdb
    - name: Test with pytest
      run: |
        poetry run pytest
